In [1]:
import numpy as np
import glob
import os
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Flatten, Dropout
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping

In [2]:
#GPU 사용하도록 설정
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

In [3]:
gesture = {
    0:"A", 1:"B", 2:"C", 3:"D", 4:"E", 5:"F", 6:"G", 7:"H", 8:"I", 9:"J", 10:"K", 11:"L", 12:"M", 13:"N",
    14:"O", 15:"P", 16:"Q", 17:"R", 18:"S", 19:"T", 20:"U", 21:"V", 22:"W", 23:"X", 24:"Y", 25:"Z"
}

In [4]:
path = "./hand_dataset/*.npy"

In [5]:
file_list = glob.glob(path)
file_list

['./hand_dataset\\A-1726903694.npy',
 './hand_dataset\\A-1726903766.npy',
 './hand_dataset\\A_1721720113.npy',
 './hand_dataset\\B-1726903818.npy',
 './hand_dataset\\B_1721719540.npy',
 './hand_dataset\\B_1721720254.npy',
 './hand_dataset\\C-1726903900.npy',
 './hand_dataset\\C_1721719591.npy',
 './hand_dataset\\C_1721720352.npy',
 './hand_dataset\\D-1726904014.npy',
 './hand_dataset\\D_1721719643.npy',
 './hand_dataset\\D_1721720397.npy',
 './hand_dataset\\E-1726904060.npy',
 './hand_dataset\\E_1721719690.npy',
 './hand_dataset\\E_1721720442.npy',
 './hand_dataset\\F-1726904116.npy',
 './hand_dataset\\F_1721719739.npy',
 './hand_dataset\\F_1721722482.npy',
 './hand_dataset\\G-1726904362.npy',
 './hand_dataset\\G_1721719786.npy',
 './hand_dataset\\G_1721722528.npy',
 './hand_dataset\\H-1726904414.npy',
 './hand_dataset\\H_1721719834.npy',
 './hand_dataset\\H_1721722613.npy',
 './hand_dataset\\I-1726904459.npy',
 './hand_dataset\\I_1721719998.npy',
 './hand_dataset\\I_1721722659.npy',
 

In [6]:
data_list = []
for file in file_list:
    print("file=", file)
    data = np.load(file)
    print("data.shape=", data[:540, :].shape)
    data_list.extend(data[:540, :])

file= ./hand_dataset\A-1726903694.npy
data.shape= (540, 79)
file= ./hand_dataset\A-1726903766.npy
data.shape= (540, 79)
file= ./hand_dataset\A_1721720113.npy
data.shape= (540, 79)
file= ./hand_dataset\B-1726903818.npy
data.shape= (540, 79)
file= ./hand_dataset\B_1721719540.npy
data.shape= (540, 79)
file= ./hand_dataset\B_1721720254.npy
data.shape= (540, 79)
file= ./hand_dataset\C-1726903900.npy
data.shape= (540, 79)
file= ./hand_dataset\C_1721719591.npy
data.shape= (540, 79)
file= ./hand_dataset\C_1721720352.npy
data.shape= (540, 79)
file= ./hand_dataset\D-1726904014.npy
data.shape= (540, 79)
file= ./hand_dataset\D_1721719643.npy
data.shape= (540, 79)
file= ./hand_dataset\D_1721720397.npy
data.shape= (540, 79)
file= ./hand_dataset\E-1726904060.npy
data.shape= (540, 79)
file= ./hand_dataset\E_1721719690.npy
data.shape= (540, 79)
file= ./hand_dataset\E_1721720442.npy
data.shape= (540, 79)
file= ./hand_dataset\F-1726904116.npy
data.shape= (540, 79)
file= ./hand_dataset\F_1721719739.npy
da

In [7]:
len(data_list)

38880

In [9]:
all_data = np.array(data_list, dtype=np.float32)
all_data

array([[ 4.9234158e-01,  9.6115118e-01, -5.2998939e-07, ...,
         4.3858547e+01,  1.1889682e+02,  0.0000000e+00],
       [ 5.1829427e-01,  7.6567298e-01, -4.9394811e-07, ...,
         5.5679295e+01,  5.2032928e+01,  0.0000000e+00],
       [ 5.3892606e-01,  7.2008771e-01, -1.8606367e-07, ...,
         1.4431424e+02,  6.3804428e+01,  0.0000000e+00],
       ...,
       [ 4.7306544e-01,  6.2992150e-01,  4.6825051e-08, ...,
         8.9414604e+01,  6.6004005e+01,  2.5000000e+01],
       [ 4.8888662e-01,  6.3018769e-01,  1.2027233e-07, ...,
         6.9013115e+01,  7.8130768e+01,  2.5000000e+01],
       [ 5.0208497e-01,  6.2503552e-01,  8.3170420e-08, ...,
         6.7569412e+01,  7.8076332e+01,  2.5000000e+01]], dtype=float32)

In [10]:
all_data.shape

(38880, 79)

In [11]:
all_data_lstm = all_data.reshape(-1, 5, 79)
all_data_lstm.shape

(7776, 5, 79)

In [12]:
X_data = all_data_lstm[:,:,:-1]
X_data

array([[[ 4.92341578e-01,  9.61151183e-01, -5.29989393e-07, ...,
          1.30777252e+02,  4.38585472e+01,  1.18896820e+02],
        [ 5.18294275e-01,  7.65672982e-01, -4.93948107e-07, ...,
          1.30593277e+02,  5.56792946e+01,  5.20329285e+01],
        [ 5.38926065e-01,  7.20087707e-01, -1.86063673e-07, ...,
          3.25502052e+01,  1.44314240e+02,  6.38044281e+01],
        [ 5.44440687e-01,  6.53261304e-01, -1.87380195e-07, ...,
          1.78087082e+01,  1.52062119e+02,  3.47539673e+01],
        [ 5.48921227e-01,  5.91867328e-01, -2.60911577e-07, ...,
          1.73126469e+01,  1.63197250e+02,  3.34668159e+01]],

       [[ 5.46441376e-01,  5.39192617e-01, -3.39433143e-07, ...,
          2.06088524e+01,  1.67759689e+02,  2.21394196e+01],
        [ 5.39980531e-01,  5.00345349e-01, -3.84503295e-07, ...,
          2.16697292e+01,  1.67811707e+02,  1.79285316e+01],
        [ 5.39938986e-01,  4.80360836e-01, -3.85743618e-07, ...,
          2.14865837e+01,  1.67894333e+02,  1.80005

In [13]:
labels = all_data_lstm[:,0,-1]
labels

array([ 0.,  0.,  0., ..., 25., 25., 25.], dtype=float32)

In [14]:
y_data = to_categorical(labels, num_classes=len(gesture))
y_data

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X_data, y_data, test_size=0.1)

In [16]:
X_train

array([[[ 5.45611024e-01,  3.50237906e-01,  7.60441253e-07, ...,
          6.62233276e+01,  1.05251236e+02,  4.47323532e+01],
        [ 5.08223236e-01,  3.73017728e-01,  6.04373838e-07, ...,
          6.38233681e+01,  7.50317230e+01,  4.57805405e+01],
        [ 5.00979125e-01,  4.21817780e-01,  5.59251077e-07, ...,
          7.29456482e+01,  6.79581604e+01,  4.55314026e+01],
        [ 5.04022837e-01,  4.40775305e-01,  5.93977518e-07, ...,
          6.44964905e+01,  6.86083450e+01,  4.58035583e+01],
        [ 5.06257892e-01,  4.54897225e-01,  6.16927196e-07, ...,
          7.22441177e+01,  6.94507523e+01,  4.38472862e+01]],

       [[ 4.33888882e-01,  4.93212998e-01, -3.02041798e-07, ...,
          2.37246914e+01,  1.34024643e+02,  2.88025665e+01],
        [ 4.26506907e-01,  4.92526352e-01, -3.10838601e-07, ...,
          2.34994965e+01,  1.29867538e+02,  3.06327171e+01],
        [ 4.17606711e-01,  4.92050052e-01, -3.21365349e-07, ...,
          2.39757729e+01,  1.27471832e+02,  2.90656

In [17]:
y_train[0:5]

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [31]:
model = Sequential()

In [32]:
model.add(LSTM(256, input_shape=(5, 78)))

In [33]:
model.add(Flatten())

In [34]:
model.add(Dense(128, activation='relu'))

In [35]:
model.add(Dropout(0.5))

In [36]:
model.add(Dense(64, activation='relu'))

In [37]:
model.add(Dropout(0.5))

In [38]:
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.5))

In [39]:
model.add(Dense(len(gesture), activation='softmax'))

In [40]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['acc'])

In [41]:
cb_checkpoint = ModelCheckpoint(filepath='./hand_lstm_train_result/', monitor='val_acc', save_best_only=True)

In [42]:
earlystopping = EarlyStopping(monitor="val_loss", patience=30)

In [43]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=100, callbacks=[cb_checkpoint, earlystopping])

Epoch 1/100
208/219 [===========================>..] - ETA: 0s - loss: 2.9665 - acc: 0.1340

INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


219/219 [==============================] - 11s 19ms/step - loss: 2.9476 - acc: 0.1389 - val_loss: 2.3531 - val_acc: 0.3175
Epoch 2/100
211/219 [===========================>..] - ETA: 0s - loss: 2.3556 - acc: 0.2475

INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


219/219 [==============================] - 3s 16ms/step - loss: 2.3491 - acc: 0.2495 - val_loss: 1.7347 - val_acc: 0.5026
Epoch 3/100
203/219 [==========================>...] - ETA: 0s - loss: 1.9613 - acc: 0.3264

INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


219/219 [==============================] - 3s 14ms/step - loss: 1.9444 - acc: 0.3310 - val_loss: 1.3094 - val_acc: 0.5540
Epoch 4/100
207/219 [===========================>..] - ETA: 0s - loss: 1.6745 - acc: 0.3860

INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


219/219 [==============================] - 3s 14ms/step - loss: 1.6722 - acc: 0.3865 - val_loss: 1.1283 - val_acc: 0.5553
Epoch 5/100
216/219 [============================>.] - ETA: 0s - loss: 1.4674 - acc: 0.4303

INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


219/219 [==============================] - 3s 14ms/step - loss: 1.4650 - acc: 0.4314 - val_loss: 0.9820 - val_acc: 0.6131
Epoch 6/100
219/219 [==============================] - 1s 4ms/step - loss: 1.3535 - acc: 0.4680 - val_loss: 0.9373 - val_acc: 0.5848
Epoch 7/100
212/219 [============================>.] - ETA: 0s - loss: 1.2626 - acc: 0.4971

INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


219/219 [==============================] - 3s 14ms/step - loss: 1.2629 - acc: 0.4971 - val_loss: 0.8539 - val_acc: 0.6260
Epoch 8/100
219/219 [==============================] - 1s 4ms/step - loss: 1.1776 - acc: 0.5113 - val_loss: 0.8276 - val_acc: 0.5874
Epoch 9/100
219/219 [==============================] - 1s 3ms/step - loss: 1.1473 - acc: 0.5306 - val_loss: 0.8085 - val_acc: 0.6054
Epoch 10/100
213/219 [============================>.] - ETA: 0s - loss: 1.1321 - acc: 0.5324

INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


219/219 [==============================] - 3s 13ms/step - loss: 1.1314 - acc: 0.5320 - val_loss: 0.7855 - val_acc: 0.6337
Epoch 11/100
213/219 [============================>.] - ETA: 0s - loss: 1.0872 - acc: 0.5421

INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


219/219 [==============================] - 3s 13ms/step - loss: 1.0851 - acc: 0.5432 - val_loss: 0.7983 - val_acc: 0.6401
Epoch 12/100
214/219 [============================>.] - ETA: 0s - loss: 1.1009 - acc: 0.5473

INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


219/219 [==============================] - 3s 14ms/step - loss: 1.0977 - acc: 0.5483 - val_loss: 0.7920 - val_acc: 0.6440
Epoch 13/100
209/219 [===========================>..] - ETA: 0s - loss: 1.0374 - acc: 0.5621

INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


219/219 [==============================] - 3s 13ms/step - loss: 1.0380 - acc: 0.5627 - val_loss: 0.7706 - val_acc: 0.6491
Epoch 14/100
216/219 [============================>.] - ETA: 0s - loss: 1.0047 - acc: 0.5757

INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


219/219 [==============================] - 3s 15ms/step - loss: 1.0054 - acc: 0.5752 - val_loss: 0.7511 - val_acc: 0.6774
Epoch 15/100
216/219 [============================>.] - ETA: 0s - loss: 0.9903 - acc: 0.5802

INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


219/219 [==============================] - 3s 14ms/step - loss: 0.9889 - acc: 0.5810 - val_loss: 0.7745 - val_acc: 0.7185
Epoch 16/100
219/219 [==============================] - 1s 4ms/step - loss: 0.9635 - acc: 0.5952 - val_loss: 0.7068 - val_acc: 0.6812
Epoch 17/100
219/219 [==============================] - 1s 4ms/step - loss: 0.9586 - acc: 0.5917 - val_loss: 0.7423 - val_acc: 0.6427
Epoch 18/100
208/219 [===========================>..] - ETA: 0s - loss: 0.9514 - acc: 0.6044

INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


219/219 [==============================] - 3s 13ms/step - loss: 0.9492 - acc: 0.6042 - val_loss: 0.6997 - val_acc: 0.7237
Epoch 19/100
219/219 [==============================] - 1s 4ms/step - loss: 0.9213 - acc: 0.6179 - val_loss: 0.6818 - val_acc: 0.7082
Epoch 20/100
219/219 [==============================] - 1s 4ms/step - loss: 0.9022 - acc: 0.6268 - val_loss: 0.6641 - val_acc: 0.7211
Epoch 21/100
208/219 [===========================>..] - ETA: 0s - loss: 0.8827 - acc: 0.6343

INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


219/219 [==============================] - 3s 14ms/step - loss: 0.8904 - acc: 0.6333 - val_loss: 0.6381 - val_acc: 0.7275
Epoch 22/100
209/219 [===========================>..] - ETA: 0s - loss: 0.8874 - acc: 0.6320

INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


219/219 [==============================] - 3s 14ms/step - loss: 0.8822 - acc: 0.6346 - val_loss: 0.5973 - val_acc: 0.7648
Epoch 23/100
214/219 [============================>.] - ETA: 0s - loss: 0.8707 - acc: 0.6497

INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


219/219 [==============================] - 3s 15ms/step - loss: 0.8712 - acc: 0.6488 - val_loss: 0.6024 - val_acc: 0.7853
Epoch 24/100
219/219 [==============================] - 1s 4ms/step - loss: 0.8605 - acc: 0.6486 - val_loss: 0.5760 - val_acc: 0.7853
Epoch 25/100
206/219 [===========================>..] - ETA: 0s - loss: 0.7961 - acc: 0.6778

INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


219/219 [==============================] - 3s 13ms/step - loss: 0.7969 - acc: 0.6779 - val_loss: 0.5599 - val_acc: 0.7995
Epoch 26/100
219/219 [==============================] - 1s 4ms/step - loss: 0.8342 - acc: 0.6632 - val_loss: 0.5490 - val_acc: 0.7776
Epoch 27/100
219/219 [==============================] - 1s 4ms/step - loss: 0.8452 - acc: 0.6613 - val_loss: 0.5395 - val_acc: 0.7545
Epoch 28/100
219/219 [==============================] - 1s 4ms/step - loss: 0.8281 - acc: 0.6753 - val_loss: 0.5451 - val_acc: 0.7763
Epoch 29/100
219/219 [==============================] - 1s 4ms/step - loss: 0.8020 - acc: 0.6729 - val_loss: 0.5094 - val_acc: 0.7866
Epoch 30/100
219/219 [==============================] - ETA: 0s - loss: 0.7696 - acc: 0.6931

INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


219/219 [==============================] - 3s 13ms/step - loss: 0.7696 - acc: 0.6931 - val_loss: 0.4959 - val_acc: 0.8342
Epoch 31/100
219/219 [==============================] - 1s 4ms/step - loss: 0.7862 - acc: 0.6905 - val_loss: 0.5645 - val_acc: 0.8213
Epoch 32/100
219/219 [==============================] - 1s 4ms/step - loss: 0.7977 - acc: 0.6915 - val_loss: 0.5321 - val_acc: 0.8252
Epoch 33/100
219/219 [==============================] - 1s 4ms/step - loss: 0.7883 - acc: 0.6935 - val_loss: 0.5256 - val_acc: 0.8201
Epoch 34/100
219/219 [==============================] - 1s 4ms/step - loss: 0.7331 - acc: 0.7103 - val_loss: 0.4686 - val_acc: 0.7956
Epoch 35/100
219/219 [==============================] - 1s 4ms/step - loss: 0.7226 - acc: 0.7182 - val_loss: 0.4701 - val_acc: 0.8098
Epoch 36/100
217/219 [============================>.] - ETA: 0s - loss: 0.7535 - acc: 0.7100

INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


219/219 [==============================] - 3s 14ms/step - loss: 0.7539 - acc: 0.7101 - val_loss: 0.4661 - val_acc: 0.8432
Epoch 37/100
213/219 [============================>.] - ETA: 0s - loss: 0.7210 - acc: 0.7190

INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


219/219 [==============================] - 3s 14ms/step - loss: 0.7204 - acc: 0.7191 - val_loss: 0.4555 - val_acc: 0.8573
Epoch 38/100
219/219 [==============================] - 1s 4ms/step - loss: 0.7350 - acc: 0.7153 - val_loss: 0.4677 - val_acc: 0.7995
Epoch 39/100
219/219 [==============================] - 1s 4ms/step - loss: 0.7422 - acc: 0.7166 - val_loss: 0.4443 - val_acc: 0.8213
Epoch 40/100
219/219 [==============================] - 1s 4ms/step - loss: 0.7273 - acc: 0.7192 - val_loss: 0.4455 - val_acc: 0.8393
Epoch 41/100
219/219 [==============================] - 1s 4ms/step - loss: 0.7107 - acc: 0.7301 - val_loss: 0.4451 - val_acc: 0.8445
Epoch 42/100
215/219 [============================>.] - ETA: 0s - loss: 0.6801 - acc: 0.7419

INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


219/219 [==============================] - 3s 13ms/step - loss: 0.6826 - acc: 0.7419 - val_loss: 0.3983 - val_acc: 0.8728
Epoch 43/100
219/219 [==============================] - 1s 4ms/step - loss: 0.6549 - acc: 0.7552 - val_loss: 0.4211 - val_acc: 0.8522
Epoch 44/100
219/219 [==============================] - 1s 3ms/step - loss: 0.6660 - acc: 0.7435 - val_loss: 0.3942 - val_acc: 0.8676
Epoch 45/100
219/219 [==============================] - 1s 3ms/step - loss: 0.6679 - acc: 0.7525 - val_loss: 0.3741 - val_acc: 0.8650
Epoch 46/100
219/219 [==============================] - 1s 3ms/step - loss: 0.6534 - acc: 0.7572 - val_loss: 0.3724 - val_acc: 0.8625
Epoch 47/100
219/219 [==============================] - 1s 3ms/step - loss: 0.6795 - acc: 0.7495 - val_loss: 0.3977 - val_acc: 0.8638
Epoch 48/100
217/219 [============================>.] - ETA: 0s - loss: 0.6724 - acc: 0.7539

INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


219/219 [==============================] - 3s 13ms/step - loss: 0.6719 - acc: 0.7542 - val_loss: 0.3703 - val_acc: 0.8805
Epoch 49/100
219/219 [==============================] - 1s 4ms/step - loss: 0.6578 - acc: 0.7592 - val_loss: 0.3896 - val_acc: 0.8560
Epoch 50/100
219/219 [==============================] - 1s 3ms/step - loss: 0.6478 - acc: 0.7615 - val_loss: 0.3396 - val_acc: 0.8740
Epoch 51/100
219/219 [==============================] - 1s 3ms/step - loss: 0.6236 - acc: 0.7752 - val_loss: 0.3664 - val_acc: 0.8599
Epoch 52/100
219/219 [==============================] - 1s 3ms/step - loss: 0.6377 - acc: 0.7636 - val_loss: 0.3363 - val_acc: 0.8715
Epoch 53/100
219/219 [==============================] - 1s 3ms/step - loss: 0.6512 - acc: 0.7688 - val_loss: 0.3516 - val_acc: 0.8612
Epoch 54/100
198/219 [==========================>...] - ETA: 0s - loss: 0.5953 - acc: 0.7824

INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


219/219 [==============================] - 3s 12ms/step - loss: 0.6001 - acc: 0.7828 - val_loss: 0.3619 - val_acc: 0.8907
Epoch 55/100
219/219 [==============================] - 1s 4ms/step - loss: 0.6020 - acc: 0.7824 - val_loss: 0.3303 - val_acc: 0.8715
Epoch 56/100
219/219 [==============================] - 1s 3ms/step - loss: 0.6174 - acc: 0.7744 - val_loss: 0.3196 - val_acc: 0.8882
Epoch 57/100
219/219 [==============================] - 1s 3ms/step - loss: 0.6226 - acc: 0.7811 - val_loss: 0.3486 - val_acc: 0.8650
Epoch 58/100
219/219 [==============================] - 1s 3ms/step - loss: 0.6120 - acc: 0.7809 - val_loss: 0.3461 - val_acc: 0.8689
Epoch 59/100
219/219 [==============================] - 1s 3ms/step - loss: 0.5962 - acc: 0.7841 - val_loss: 0.3223 - val_acc: 0.8663
Epoch 60/100
204/219 [==========================>...] - ETA: 0s - loss: 0.5833 - acc: 0.7808

INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


219/219 [==============================] - 3s 13ms/step - loss: 0.5830 - acc: 0.7829 - val_loss: 0.3275 - val_acc: 0.9049
Epoch 61/100
219/219 [==============================] - 1s 4ms/step - loss: 0.6255 - acc: 0.7761 - val_loss: 0.3131 - val_acc: 0.8856
Epoch 62/100
219/219 [==============================] - 1s 3ms/step - loss: 0.6099 - acc: 0.7819 - val_loss: 0.3101 - val_acc: 0.8702
Epoch 63/100
219/219 [==============================] - 1s 3ms/step - loss: 0.5824 - acc: 0.7921 - val_loss: 0.2888 - val_acc: 0.8985
Epoch 64/100
219/219 [==============================] - 1s 3ms/step - loss: 0.5434 - acc: 0.8039 - val_loss: 0.3126 - val_acc: 0.8920
Epoch 65/100
219/219 [==============================] - 1s 3ms/step - loss: 0.5596 - acc: 0.8024 - val_loss: 0.3245 - val_acc: 0.8779
Epoch 66/100
219/219 [==============================] - 1s 3ms/step - loss: 0.5727 - acc: 0.8011 - val_loss: 0.2949 - val_acc: 0.8959
Epoch 67/100
219/219 [==============================] - 1s 3ms/step - loss

INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


219/219 [==============================] - 3s 13ms/step - loss: 0.5624 - acc: 0.8035 - val_loss: 0.2801 - val_acc: 0.9190
Epoch 76/100
219/219 [==============================] - 1s 5ms/step - loss: 0.5304 - acc: 0.8195 - val_loss: 0.2787 - val_acc: 0.9126
Epoch 77/100
219/219 [==============================] - 1s 4ms/step - loss: 0.5161 - acc: 0.8258 - val_loss: 0.3151 - val_acc: 0.8766
Epoch 78/100
219/219 [==============================] - 1s 4ms/step - loss: 0.5410 - acc: 0.8117 - val_loss: 0.2636 - val_acc: 0.9139
Epoch 79/100
219/219 [==============================] - 1s 4ms/step - loss: 0.5464 - acc: 0.8152 - val_loss: 0.3008 - val_acc: 0.8856
Epoch 80/100
219/219 [==============================] - 1s 4ms/step - loss: 0.5465 - acc: 0.8084 - val_loss: 0.2893 - val_acc: 0.8907
Epoch 81/100
219/219 [==============================] - 1s 4ms/step - loss: 0.5235 - acc: 0.8218 - val_loss: 0.2714 - val_acc: 0.9100
Epoch 82/100
219/219 [==============================] - 1s 4ms/step - loss

INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


219/219 [==============================] - 3s 13ms/step - loss: 0.5153 - acc: 0.8252 - val_loss: 0.2526 - val_acc: 0.9293
Epoch 94/100
219/219 [==============================] - 1s 4ms/step - loss: 0.4845 - acc: 0.8417 - val_loss: 0.2613 - val_acc: 0.9165
Epoch 95/100
219/219 [==============================] - 1s 3ms/step - loss: 0.4770 - acc: 0.8418 - val_loss: 0.2561 - val_acc: 0.9203
Epoch 96/100
219/219 [==============================] - 1s 3ms/step - loss: 0.5095 - acc: 0.8395 - val_loss: 0.2778 - val_acc: 0.9075
Epoch 97/100
216/219 [============================>.] - ETA: 0s - loss: 0.4698 - acc: 0.8436

INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


INFO:tensorflow:Assets written to: ./hand_lstm_train_result\assets


219/219 [==============================] - 3s 13ms/step - loss: 0.4693 - acc: 0.8440 - val_loss: 0.2299 - val_acc: 0.9319
Epoch 98/100
219/219 [==============================] - 1s 5ms/step - loss: 0.4818 - acc: 0.8391 - val_loss: 0.2756 - val_acc: 0.9216
Epoch 99/100
219/219 [==============================] - 1s 4ms/step - loss: 0.5290 - acc: 0.8228 - val_loss: 0.2694 - val_acc: 0.9139
Epoch 100/100
219/219 [==============================] - 1s 4ms/step - loss: 0.5021 - acc: 0.8378 - val_loss: 0.2984 - val_acc: 0.9165
